contexts:
  default:
    defaultProvider: talos
    providers:
      docker:
        creationTimestamp: "2025-10-01T23:22:01Z"
        initialized: true
        options:
          DOCKER_BUILDER:
            userProvided: true
          DOCKER_HOST:
            userProvided: true
            value: unix:///Users/simon/.docker/run/docker.sock
          DOCKER_PATH:
            value: docker
          INACTIVITY_TIMEOUT: {}
      kubernetes:
        creationTimestamp: "2025-10-22T09:42:47Z"
        initialized: true
        options:
          ARCHITECTURE: {}
          CLUSTER_ROLE: {}
          CREATE_NAMESPACE:
            value: "true"
          DISK_SIZE:
            value: 10Gi
          DOCKERLESS_DISABLED:
            value: "false"
          DOCKERLESS_IMAGE: {}
          INACTIVITY_TIMEOUT: {}
          KUBERNETES_CONFIG: {}
          KUBERNETES_CONTEXT: {}
          KUBERNETES_NAMESPACE:
            value: devpod
          KUBERNETES_PULL_SECRETS_ENABLED:
            value: "true"
          LABELS: {}
          NODE_SELECTOR: {}
          POD_MANIFEST_TEMPLATE: {}
          POD_TIMEOUT:
            value: 10m
          PVC_ACCESS_MODE: {}
          PVC_ANNOTATIONS: {}
          RESOURCES: {}
          SERVICE_ACCOUNT: {}
          STORAGE_CLASS: {}
          STRICT_SECURITY:
            value: "false"
          WORKSPACE_VOLUME_MOUNT: {}
defaultContext: default
