# Kör kommandot i ett shell och starta om processen vid förändringar
[command]
shell = true
restart = true
# Viktigt: force för att alltid applicera, även om filer redan finns
cmd = "chezmoi apply --force"

[watch]
# Bevakade paths – Chezmoi's data + config
paths = [
  # Chezmoi source state (där dina dotfiles bor)
  "~/.local/share/chezmoi",
  # Chezmoi config
  "~/.config/chezmoi",
]

# Ignorera typiska mappar/filer som inte ska trigga apply
ignore = [
  "**/.git/**",
  "**/.DS_Store",
  "**/*~",
  "**/#*#",
  "**/*.swp",
  "**/*.swo",
  # Ignorera build/outputs om du råkar ha sådant i source state
  "**/dist/**",
  "**/node_modules/**",
]

# Debounce (vänta 500 ms efter sista ändringen innan körning)
debounce = "500ms"

# Rensa terminalen mellan körningar (valfritt)
clear = true

# Rekursiv övervakning
recursive = true
